const LOCATION_OPTIONS = {
    "Andhra Pradesh": ["Amaravati", "Anantapur", "Guntur", "Kakinada", "Kurnool", "Nellore", "Rajahmundry", "Tirupati", "Vijayawada", "Visakhapatnam"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro"],
    Assam: ["Dibrugarh", "Guwahati", "Jorhat", "Silchar", "Tezpur"],
    Bihar: ["Bhagalpur", "Darbhanga", "Gaya", "Muzaffarpur", "Patna", "Purnia"],
    Chhattisgarh: ["Bilaspur", "Durg", "Jagdalpur", "Korba", "Raipur", "Rajnandgaon"],
    Goa: ["Madgaon", "Mapusa", "Panaji", "Ponda", "Vasco da Gama"],
    Gujarat: ["Ahmedabad", "Bhavnagar", "Gandhinagar", "Jamnagar", "Rajkot", "Surat", "Vadodara"],
    Haryana: ["Ambala", "Faridabad", "Gurugram", "Hisar", "Karnal", "Panipat", "Rohtak"],
    "Himachal Pradesh": ["Dharamshala", "Hamirpur", "Mandi", "Shimla", "Solan"],
    Jharkhand: ["Bokaro", "Dhanbad", "Hazaribagh", "Jamshedpur", "Ranchi"],
    Karnataka: ["Belagavi", "Bengaluru", "Davanagere", "Hubballi", "Kalaburagi", "Mangaluru", "Mysuru", "Shivamogga"],
    Kerala: ["Kannur", "Kochi", "Kollam", "Kozhikode", "Thiruvananthapuram", "Thrissur"],
    "Madhya Pradesh": ["Bhopal", "Gwalior", "Indore", "Jabalpur", "Sagar", "Ujjain"],
    Maharashtra: ["Amravati", "Aurangabad", "Kolhapur", "Mumbai", "Nagpur", "Nashik", "Pune", "Solapur", "Thane"],
    Manipur: ["Bishnupur", "Churachandpur", "Imphal", "Thoubal", "Ukhrul"],
    Meghalaya: ["Jowai", "Shillong", "Tura", "Williamnagar"],
    Mizoram: ["Aizawl", "Champhai", "Kolasib", "Lunglei"],
    Nagaland: ["Dimapur", "Kohima", "Mokokchung", "Tuensang"],
    Odisha: ["Balasore", "Berhampur", "Bhubaneswar", "Cuttack", "Puri", "Rourkela", "Sambalpur"],
    Punjab: ["Amritsar", "Bathinda", "Jalandhar", "Ludhiana", "Mohali", "Patiala"],
    Rajasthan: ["Ajmer", "Bikaner", "Jaipur", "Jodhpur", "Kota", "Udaipur"],
    Sikkim: ["Gangtok", "Gyalshing", "Mangan", "Namchi"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Salem", "Thanjavur", "Tiruchirappalli", "Tirunelveli", "Vellore"],
    Telangana: ["Hyderabad", "Karimnagar", "Khammam", "Nizamabad", "Warangal"],
    Tripura: ["Agartala", "Dharmanagar", "Kailashahar", "Udaipur"],
    "Uttar Pradesh": ["Agra", "Aligarh", "Ghaziabad", "Kanpur", "Lucknow", "Meerut", "Noida", "Prayagraj", "Varanasi"],
    Uttarakhand: ["Dehradun", "Haldwani", "Haridwar", "Rishikesh", "Roorkee"],
    "West Bengal": ["Asansol", "Durgapur", "Howrah", "Kolkata", "Siliguri"],
    "Andaman and Nicobar Islands": ["Port Blair"],
    Chandigarh: ["Chandigarh"],
    "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa"],
    Delhi: ["Central Delhi", "Dwarka", "New Delhi", "North Delhi", "Rohini", "South Delhi"],
    "Jammu and Kashmir": ["Anantnag", "Baramulla", "Jammu", "Srinagar"],
    Ladakh: ["Kargil", "Leh"],
    Lakshadweep: ["Kavaratti"],
    Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
};
